page 50078 "Cheque Register"
{
    PageType = List;
    SourceTable = "Cheque Register";
    ApplicationArea = All;

    layout
    {
        area(content)
        {
            repeater(Group)
            {
                field("Cheque No."; Rec."Cheque No.")
                {
                    ApplicationArea = All;
                    ToolTip = 'Specifies the value of the Cheque No. field';
                }
                field("Bank Account No."; Rec."Bank Account No.")
                {
                    ApplicationArea = All;
                    ToolTip = 'Specifies the value of the Bank Account No. field';
                }
                field("Entry Status"; Rec."Entry Status")
                {
                    ApplicationArea = All;
                    ToolTip = 'Specifies the value of the Entry Status field';
                }
                field("Date Generated"; Rec."Date Generated")
                {
                    ApplicationArea = All;
                    ToolTip = 'Specifies the value of the Date Generated field';
                }
                field("User ID"; Rec."User ID")
                {
                    Caption = 'Generated By';
                    ApplicationArea = All;
                    ToolTip = 'Specifies the value of the Generated By field';
                }
            }
        }
    }

    actions
    {
        area(processing)
        {
            group(Action12)
            {
                action(Generate)
                {
                    Caption = 'Generate Cheque Nos';
                    Image = CreateSerialNo;
                    RunObject = report "Generate Cheque Nos";
                    ApplicationArea = All;
                    ToolTip = 'Executes the Generate Cheque Nos action';

                    trigger OnAction()
                    begin
                        // ChequeRegister.RESET;
                        // ChequeRegister.SETRANGE(ChequeRegister."Bank Account No.","Bank Account No.");
                        // IF ChequeRegister.FIND THEN
                        //  BEGIN
                        //    REPORT.RUN(report::"Generate Cheque Nos",TRUE,FALSE,ChequeRegister);
                        //  END;
                    end;
                }
            }
        }
        area(Promoted)
        {
            group(Category_Process)
            {
                actionref(Generate_Promoted; Generate)
                {
                }
            }
        }
    }
}


